# Generated by Django 5.0.6 on 2024-07-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_category_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flooring_type', models.CharField(choices=[('vinyl', 'Vinyl'), ('wood', 'Wood'), ('carpet', 'Carpet'), ('tile', 'Tile'), ('laminate', 'Laminate'), ('vinyl_sheet', 'Vinyl Sheet')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
