# Generated by Django 5.0.6 on 2024-07-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
