# Generated by Django 5.0.6 on 2024-08-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_material_delete_product_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
